services:
  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:Z
      - prometheus-data:/prometheus:Z
    restart: unless-stopped

  loki:
    image: docker.io/grafana/loki:3.5.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yaml:Z
      - loki-data:/var/lib/loki:Z
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  grafana:
    image: docker.io/grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana:Z
    restart: unless-stopped

volumes:
  prometheus-data:
  loki-data:
  grafana-data:
